### ISSUE TITLE
Custom domain protocol drop-downs all white

### ISSUE THREAD

**Issue by presswizards** [this-is-rafa/sendy-dark-theme#2]
It seems select elements are all white in certain areas, I see it in the custom domain protocol drop-downs.

I added !important to fix it:
select {
    background-color: #272c35 !important;
    border-color: #1f232a !important;
    color: #e9e9e9 !important;
}

**Comment by this-is-rafa** [comment]
Thanks much for pointing this out and the fix. I've pushed an update.
